---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kubeconductor-greedykomodo-v1alpha1-dagrun
  failurePolicy: Fail
  name: mdagrun.kb.io
  rules:
  - apiGroups:
    - kubeconductor.greedykomodo
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dagruns
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kubeconductor-greedykomodo-v1alpha1-dagrun
  failurePolicy: Fail
  name: vdagrun.kb.io
  rules:
  - apiGroups:
    - kubeconductor.greedykomodo
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dagruns
  sideEffects: None
