apiVersion: v1
kind: Pod
metadata:
  name: pg-client
  namespace: default
spec:
  restartPolicy: Never
  containers:
  - name: psql
    image: registry-1.docker.io/bitnami/postgresql:latest
    env:
      - name: PGPASSWORD
        valueFrom:
          secretKeyRef:
            name: postgres-postgresql
            key: postgres-password
    command: ["sh", "-c", "psql -h postgres-postgresql -U postgres -c \"CREATE DATABASE kontroler;\""]
