{{ if .Values.ui.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.ui.name }}
  labels:
    {{- include "kontroler.ui.labels" . | nindent 4 }}
spec:
  {{- if not .Values.ui.autoscaling.enabled }}
  replicas: {{ .Values.ui.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kontroler.ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.ui.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kontroler.ui.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{ if .Values.ui.serviceAccount.create }}
      serviceAccountName: {{ .Values.ui.serviceAccount.name }}
      {{ end }}
      securityContext:
        {{- toYaml .Values.ui.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.ui.name }}-kontroler-ui
          securityContext:
            {{- toYaml .Values.ui.securityContext | nindent 12 }}
          image: {{ .Values.ui.image }}
          imagePullPolicy: {{ .Values.ui.imagePullPolicy }}
          env:
          - name: API_URL
            value: {{ .Values.ui.env.API_URL }}
          - name: WS_URL
            value: {{ .Values.ui.env.WS_URL }}
          ports:
            - name: http
              containerPort: {{ .Values.ui.service.port }}
              protocol: TCP
          # TODO: Allow for probes to be used with mtls
          {{ if not .Values.ui.nginx.mtls.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{ end }}
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            {{ if .Values.ui.nginx.mtls.enabled }}
            - name: mtls-ca-cert-volume
              mountPath: /etc/nginx/ssl/ca.crt
              subPath: ca.crt
            - name: mtls-cert-volume
              mountPath: /etc/nginx/ssl/tls.crt
              subPath: tls.crt
            - name: mtls-key-volume
              mountPath: /etc/nginx/ssl/tls.key
              subPath: tls.key
            {{ end }}
            {{ if and .Values.ui.nginx.reverseProxy.enabled .Values.server.mtls.enabled }}
            - name: mtls-ca-cert-volume-reverse
              mountPath: /etc/nginx/client/ca.crt
              subPath: ca.crt
            - name: mtls-cert-volume-reverse
              mountPath: /etc/nginx/client/tls.crt
              subPath: tls.crt
            - name: mtls-key-volume-reverse
              mountPath: /etc/nginx/client/tls.key
              subPath: tls.key
            {{ end }}
          resources:
            {{- toYaml .Values.ui.resources | nindent 12 }}
      volumes:
        - name: nginx-config-volume
          configMap:
            name: {{ .Values.ui.name }}-nginx-config
        {{ if .Values.ui.nginx.mtls.enabled }}
        - name: mtls-ca-cert-volume
          secret:
            secretName: {{ .Values.ui.nginx.mtls.certs.caCertSecretName }}
        - name: mtls-cert-volume
          secret:
            secretName: {{ .Values.ui.nginx.mtls.certs.certSecretName }}
        - name: mtls-key-volume
          secret:
            secretName: {{ .Values.ui.nginx.mtls.certs.keySecretName }}
        {{ end }}
        {{ if and .Values.ui.nginx.reverseProxy.enabled .Values.server.mtls.enabled }}
        - name: mtls-ca-cert-volume-reverse
          secret:
            secretName: {{ .Values.ui.nginx.reverseProxy.caCertSecretName }}
        - name: mtls-cert-volume-reverse
          secret:
            secretName: {{ .Values.ui.nginx.reverseProxy.certSecretName }}
        - name: mtls-key-volume-reverse
          secret:
            secretName: {{ .Values.ui.nginx.reverseProxy.keySecretName }}
        {{ end }}
      {{- with .Values.ui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end }}