apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.ui.name }}-nginx-config
  labels:
    {{- include "kontroler.ui.labels" . | nindent 4 }}
data:
  nginx.conf: |-
    {{ if .Values.ui.nginx.configOverride }}
    {{ .Values.ui.nginx.configOverride }}
    {{ else }}
    user  nginx;
    worker_processes  auto;

    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        #gzip  on;

        server {
            {{- if .Values.ui.nginx.mtls.enabled }}
            listen 3000 ssl; 
            {{ else }}
            listen 3000; 
            {{ end }}

            server_name localhost;

            {{- if .Values.ui.nginx.mtls.enabled }}

            ssl_certificate /etc/nginx/ssl/tls.crt;
            ssl_certificate_key /etc/nginx/ssl/tls.key; 
            
            ssl_client_certificate /etc/nginx/ssl/ca.crt; 

            {{- if .Values.ui.nginx.mtls.insecure }}
            ssl_verify_client optional_no_ca; 
            {{- else }}
            ssl_verify_client on;  
            ssl_verify_depth 2; 
            {{- end }}

            {{- else }}
            ssl_verify_client off; 
            {{- end }}

            # Serve the env-config.js that gets dynamically generated
            location /env-config.js {
                root /usr/share/nginx/html;
            }

            {{ if .Values.ui.nginx.reverseProxy.enabled }}
            # Only proxy requests starting with /api
            location /api {
                # Proxy requests to backend server
                {{ if .Values.server.mtls.enabled }}
                proxy_pass https://{{ .Values.server.name }}.{{ .Release.Namespace }}.svc.cluster.local:8080;
                proxy_ssl_certificate /etc/nginx/client/tls.crt;
                proxy_ssl_certificate_key /etc/nginx/client/tls.key;
                proxy_ssl_trusted_certificate /etc/nginx/client/ca.crt;
                {{- if .Values.ui.nginx.mtls.insecure }}
                proxy_ssl_verify off;  # Uncomment for testing if SSL issues arise
                {{ else }}
                proxy_ssl_verify on;  # Uncomment for testing if SSL issues arise
                {{ end }}
                {{ else }} 
                proxy_pass http://{{ .Values.server.name }}.{{ .Release.Namespace }}.svc.cluster.local:8080;
                {{ end }}

                # Additional headers for forwarding client info
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
            {{ end }}

            # Serve the SPA (SolidJS app)
            location / {
                root /usr/share/nginx/html;
                try_files $uri $uri/ /index.html =404; 
            }

            # Serve static files directly (e.g., CSS, JS, images, fonts)
            location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
                root /usr/share/nginx/html; 
                try_files $uri =404;  
                expires max;  # Cache static assets
                log_not_found off;  # Don't log missing files like favicons
            }

            location /healthz {
                # Disable mTLS for this specific endpoint
                root /usr/share/nginx/html;
                return 200 "Healthy\n";
            }

            # Error handling
            error_page 500 502 503 504 /50x.html;
            location = /50x.html {
                root /usr/share/nginx/html;
            }
        }

        include /etc/nginx/conf.d/*.conf;
    }
    {{ end }}

