# permissions for end users to edit dags.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: dag-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: dag-editor-role
rules:
- apiGroups:
  - kubeconductor.greedykomodo
  resources:
  - dags
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeconductor.greedykomodo
  resources:
  - dags/status
  verbs:
  - get
