---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kubeconductor.greedykomodo
  resources:
  - dagruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeconductor.greedykomodo
  resources:
  - dagruns/finalizers
  verbs:
  - update
- apiGroups:
  - kubeconductor.greedykomodo
  resources:
  - dagruns/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kubeconductor.greedykomodo
  resources:
  - dags
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeconductor.greedykomodo
  resources:
  - dags/finalizers
  verbs:
  - update
- apiGroups:
  - kubeconductor.greedykomodo
  resources:
  - dags/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kubeconductor.greedykomodo
  resources:
  - schedules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeconductor.greedykomodo
  resources:
  - schedules/finalizers
  verbs:
  - update
- apiGroups:
  - kubeconductor.greedykomodo
  resources:
  - schedules/status
  verbs:
  - get
  - patch
  - update
