{{ if .Values.server.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-log-streaming
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: kontroler
rules:
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/instance: manager-rolebinding-pod
    app.kubernetes.io/name: clusterrolebinding-pod
    app.kubernetes.io/part-of: kontroler
  name: pod-log-streaming-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-log-streaming
subjects:
- kind: ServiceAccount
  name: {{ .Values.server.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
{{ end }}