{{ if .Values.server.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.server.name }}
  labels:
    {{- include "kontroler.server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      protocol: TCP
      targetPort: http
      name: http
    - port: 2112
      protocol: TCP
      targetPort: metrics
      name: metrics
  selector:
    {{- include "kontroler.server.selectorLabels" . | nindent 4 }}
{{ end }}