{{ if .Values.controller.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-event-role
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: kontroler
    app.kubernetes.io/component: events
rules:
- apiGroups:
  - ""  # Core API group
  resources:
  - events
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""  # Core API group
  resources:
  - events/status
  verbs:
  - get
- apiGroups:
  - ""  # Core API group
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/instance: event-rolebinding
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/part-of: kontroler
  name: operator-event-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: operator-event-role
subjects:
- kind: ServiceAccount
  name: operator-controller-manager
  namespace: {{ .Release.Namespace }}
{{ end }}
