{{ if and .Values.certManager.enabled .Values.controller.enabled .Values.certManager.issuer.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app.kubernetes.io/component: certificate
    app.kubernetes.io/instance: serving-cert
    app.kubernetes.io/name: certificate
    app.kubernetes.io/part-of: kontroler
  name: operator-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
spec:
{{ toYaml .Values.certManager.issuer.spec | indent 2 }}
{{ end }}