{{ if .Values.controller.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/instance: controller-manager-sa
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/part-of: kontroler
  name: operator-controller-manager
{{ end }}