apiVersion: kontroler.greedykomodo/v1alpha1
kind: Schedule
metadata:
  name: schedule-sample
spec:
  cronSchedule: "*/1 * * * *"
  imageName: "alpine:latest"
  command: ["sh", "-c"]
  args:
    ["if [ $((RANDOM%2)) -eq 0 ]; then echo 'Hello, World!'; else exit 1; fi"]
  backoff:
    limit: 3
    # throws an error if limit does not make the delays if used
    # is optional, if empty, it is ignored
    # s,m,h units, avoids having to use regex which is slow
    delays: [0s, 1s, 2s]
  # conditional is optional
  conditional:
    enabled: true
    retryCodes: [8]
