# Build a minimal worker binary and package with distroless
FROM docker.io/library/golang:1.25 AS builder
WORKDIR /workspace
COPY go.mod go.sum ./
RUN go mod download
COPY ./cmd/worker ./cmd/worker
COPY ./internal ./internal
COPY ./api ./api
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o /workspace/worker ./cmd/worker/main.go

FROM gcr.io/distroless/static:nonroot
COPY --from=builder /workspace/worker /worker
USER nonroot
ENTRYPOINT ["/worker"]
